const std = @import("std");
const schema = @import("schema.zig");
const default_partition = @import("default.zig");

pub const PartitionType = schema.PartitionType;
pub const Partition = schema.Partition;
pub const Table = schema.Table;

pub const default_table = default_partition.table;

pub const ValidateError = error{MissingFactoryAppPartition};

pub fn validateEntries(entries: []const Partition) ValidateError!void {
    for (entries) |entry| {
        if (std.mem.eql(u8, entry.name, "factory") and entry.kind == .app) return;
    }
    return error.MissingFactoryAppPartition;
}

pub fn renderCsv(
    allocator: std.mem.Allocator,
    entries: []const Partition,
) std.mem.Allocator.Error![]u8 {
    var out = std.array_list.Managed(u8).init(allocator);
    errdefer out.deinit();

    const writer = out.writer();
    try writer.writeAll(
        "# AUTO-GENERATED BY ESPZ PARTITION GENERATOR\n" ++
            "# Name, Type, SubType, Offset, Size, Flags\n",
    );

    for (entries) |entry| {
        const flags = entry.flags orelse "";
        const offset = entry.offset_hex orelse "";
        try writer.print(
            "{s}, {s}, {s}, {s}, {s}, {s}\n",
            .{
                entry.name,
                typeText(entry.kind),
                entry.subtype,
                offset,
                entry.size_hex,
                flags,
            },
        );
    }

    return out.toOwnedSlice();
}

fn typeText(kind: PartitionType) []const u8 {
    return switch (kind) {
        .app => "app",
        .data => "data",
    };
}

test "default partition includes factory app" {
    try validateEntries(default_table.entries);
}
