const std = @import("std");
const schema = @import("schema.zig");
const default_partition = @import("default.zig");

pub const PartitionType = schema.PartitionType;
pub const PartitionSubtype = schema.PartitionSubtype;
pub const Partition = schema.Partition;
pub const Table = schema.Table;
pub const DataSource = schema.DataSource;
pub const data = schema.data;
pub const NvsEntry = schema.NvsEntry;
pub const NvsData = schema.NvsData;
pub const NvsValue = schema.NvsValue;
pub const NvsValueType = schema.NvsValueType;

pub const default_table = default_partition.table;
pub const ResolvedPartition = struct {
    name: []const u8,
    kind: PartitionType,
    subtype: PartitionSubtype,
    offset: u32,
    size: u32,
    flags: ?[]const u8 = null,
    data: ?DataSource = null,
};

pub const ValidateError = error{MissingAppPartition};

pub fn validateEntries(entries: anytype) ValidateError!void {
    for (entries) |entry| {
        if (entry.kind == .app) {
            if (std.mem.eql(u8, entry.name, "factory")) return;
            if (entry.subtype == .ota_0) return;
        }
    }
    return error.MissingAppPartition;
}

pub fn renderCsv(allocator: std.mem.Allocator, entries: anytype) std.mem.Allocator.Error![]u8 {
    var out = std.array_list.Managed(u8).init(allocator);
    errdefer out.deinit();

    const writer = out.writer();
    try writer.writeAll(
        "# AUTO-GENERATED BY ESPZ PARTITION GENERATOR\n" ++
            "# Name, Type, SubType, Offset, Size, Flags\n",
    );

    for (entries) |entry| {
        const flags = entry.flags orelse "";
        try writer.print(
            "{s}, {s}, {s}, {s}, {s}, {s}\n",
            .{
                entry.name,
                typeText(entry.kind),
                try subtypeTextAlloc(allocator, entry.subtype),
                try formatOptionalHexAlloc(allocator, entry.offset),
                try formatHexAlloc(allocator, entry.size),
                flags,
            },
        );
    }

    return out.toOwnedSlice();
}

pub fn resolveEntriesAlloc(allocator: std.mem.Allocator, table: Table) ![]ResolvedPartition {
    const resolved = try allocator.alloc(ResolvedPartition, table.entries.len);
    var next_offset = alignToSector(table.offset + partitionTableReservedSize());

    for (table.entries, 0..) |entry, idx| {
        const resolved_offset = entry.offset orelse next_offset;
        resolved[idx] = .{
            .name = entry.name,
            .kind = entry.kind,
            .subtype = entry.subtype,
            .offset = resolved_offset,
            .size = entry.size,
            .flags = entry.flags,
            .data = entry.data,
        };
        next_offset = alignToSector(resolved_offset + entry.size);
    }

    return resolved;
}

fn typeText(kind: PartitionType) []const u8 {
    return switch (kind) {
        .app => "app",
        .data => "data",
    };
}

fn partitionTableReservedSize() u32 {
    return 0x1000;
}

fn alignToSector(value: u32) u32 {
    return (value + 0xfff) & ~@as(u32, 0xfff);
}

pub fn formatHexAlloc(allocator: std.mem.Allocator, value: u32) std.mem.Allocator.Error![]u8 {
    return std.fmt.allocPrint(allocator, "0x{x}", .{value});
}

pub fn formatOptionalHexAlloc(allocator: std.mem.Allocator, value: ?u32) std.mem.Allocator.Error![]u8 {
    if (value) |v| return formatHexAlloc(allocator, v);
    return allocator.dupe(u8, "");
}

pub fn subtypeTextAlloc(allocator: std.mem.Allocator, subtype: PartitionSubtype) std.mem.Allocator.Error![]u8 {
    return switch (subtype) {
        .factory => allocator.dupe(u8, "factory"),
        .ota => allocator.dupe(u8, "ota"),
        .ota_0 => allocator.dupe(u8, "ota_0"),
        .ota_1 => allocator.dupe(u8, "ota_1"),
        .phy => allocator.dupe(u8, "phy"),
        .nvs => allocator.dupe(u8, "nvs"),
        .spiffs => allocator.dupe(u8, "spiffs"),
        .littlefs => allocator.dupe(u8, "littlefs"),
        .custom_name => |name| allocator.dupe(u8, name),
        .custom_value => |value| std.fmt.allocPrint(allocator, "0x{x}", .{value}),
    };
}

pub fn nvsCsvAlloc(allocator: std.mem.Allocator, entries: []const NvsEntry) ![]u8 {
    var out = std.array_list.Managed(u8).init(allocator);
    errdefer out.deinit();

    const writer = out.writer();
    try writer.writeAll("key,type,encoding,value\n");

    var current_namespace: ?[]const u8 = null;
    for (entries) |entry| {
        if (current_namespace == null or !std.mem.eql(u8, current_namespace.?, entry.namespace)) {
            current_namespace = entry.namespace;
            try writer.print("{s},namespace,,\n", .{entry.namespace});
        }
        try writer.print(
            "{s},data,{s},{s}\n",
            .{
                entry.key,
                nvsEncodingText(entry.value_type),
                try nvsValueTextAlloc(allocator, entry.value),
            },
        );
    }

    return out.toOwnedSlice();
}

fn nvsEncodingText(value_type: NvsValueType) []const u8 {
    return switch (value_type) {
        .u8 => "u8",
        .i8 => "i8",
        .u16 => "u16",
        .i16 => "i16",
        .u32 => "u32",
        .i32 => "i32",
        .u64 => "u64",
        .i64 => "i64",
        .string => "string",
        .blob => "binary",
    };
}

fn nvsValueTextAlloc(allocator: std.mem.Allocator, value: NvsValue) std.mem.Allocator.Error![]u8 {
    return switch (value) {
        .signed => |v| std.fmt.allocPrint(allocator, "{d}", .{v}),
        .unsigned => |v| std.fmt.allocPrint(allocator, "{d}", .{v}),
        .str => |v| allocator.dupe(u8, v),
        .blob => |v| allocator.dupe(u8, v),
    };
}

test "default partition includes factory app" {
    try validateEntries(default_table.entries);
}
