const std = @import("std");

pub const Value = union(enum) {
    bool: bool,
    string: []const u8,
    integer: i64,
    raw: []const u8,

    pub fn eql(lhs: Value, rhs: Value) bool {
        const lhs_tag = std.meta.activeTag(lhs);
        const rhs_tag = std.meta.activeTag(rhs);
        if (lhs_tag != rhs_tag) return false;

        return switch (lhs) {
            .bool => |value| value == rhs.bool,
            .string => |value| std.mem.eql(u8, value, rhs.string),
            .integer => |value| value == rhs.integer,
            .raw => |value| std.mem.eql(u8, value, rhs.raw),
        };
    }
};

pub const Entry = struct {
    key: []const u8,
    value: Value,

    pub fn flag(key: []const u8, enabled: bool) Entry {
        return .{
            .key = key,
            .value = .{ .bool = enabled },
        };
    }

    pub fn str(key: []const u8, text: []const u8) Entry {
        return .{
            .key = key,
            .value = .{ .string = text },
        };
    }

    pub fn int(key: []const u8, number: i64) Entry {
        return .{
            .key = key,
            .value = .{ .integer = number },
        };
    }

    pub fn raw(key: []const u8, text: []const u8) Entry {
        return .{
            .key = key,
            .value = .{ .raw = text },
        };
    }

    pub fn eql(lhs: Entry, rhs: Entry) bool {
        return std.mem.eql(u8, lhs.key, rhs.key) and lhs.value.eql(rhs.value);
    }
};

pub const ModuleDoc = struct {
    name: []const u8,
    entries: []const Entry,
};

pub const RenderError = error{ConfigKeyConflict};

pub fn freeModuleDocs(allocator: std.mem.Allocator, docs: []const ModuleDoc) void {
    for (docs) |doc| {
        allocator.free(doc.entries);
    }
    allocator.free(docs);
}

pub fn render(
    allocator: std.mem.Allocator,
    modules: []const ModuleDoc,
) (std.mem.Allocator.Error || RenderError)![]u8 {
    var out = std.array_list.Managed(u8).init(allocator);
    errdefer out.deinit();

    var seen = std.StringHashMap(Entry).init(allocator);
    defer seen.deinit();

    const writer = out.writer();
    try writer.writeAll(
        "# AUTO-GENERATED BY ESPZ SDKCONFIG AGGREGATOR\n" ++
            "# edit typed config in src/*/config.zig and examples/*/board/*.zig, do not edit this file manually\n\n",
    );

    for (modules) |module| {
        try writer.print("# [{s}]\n", .{module.name});

        for (module.entries) |entry| {
            if (seen.get(entry.key)) |existing| {
                if (!existing.eql(entry)) return error.ConfigKeyConflict;
                continue;
            }

            try seen.put(entry.key, entry);
            try writeEntry(writer, entry);
            try writer.writeByte('\n');
        }

        try writer.writeByte('\n');
    }

    return out.toOwnedSlice();
}

fn writeEntry(writer: anytype, entry: Entry) !void {
    switch (entry.value) {
        .bool => |enabled| {
            if (enabled) {
                try writer.print("{s}=y", .{entry.key});
            } else {
                try writer.print("# {s} is not set", .{entry.key});
            }
        },
        .string => |text| {
            try writer.print("{s}=", .{entry.key});
            try writeQuotedString(writer, text);
        },
        .integer => |number| {
            try writer.print("{s}={d}", .{ entry.key, number });
        },
        .raw => |text| {
            try writer.print("{s}={s}", .{ entry.key, text });
        },
    }
}

fn writeQuotedString(writer: anytype, text: []const u8) !void {
    try writer.writeByte('"');
    for (text) |c| {
        switch (c) {
            '"' => try writer.writeAll("\\\""),
            '\\' => try writer.writeAll("\\\\"),
            else => try writer.writeByte(c),
        }
    }
    try writer.writeByte('"');
}

test "render prints enabled/disabled/string/integer/raw entries" {
    const docs = [_]ModuleDoc{
        .{
            .name = "core",
            .entries = &.{
                Entry.flag("CONFIG_A", true),
                Entry.flag("CONFIG_B", false),
                Entry.str("CONFIG_C", "hello"),
                Entry.int("CONFIG_D", 42),
                Entry.raw("CONFIG_E", "0x8000"),
            },
        },
    };

    const rendered = try render(std.testing.allocator, &docs);
    defer std.testing.allocator.free(rendered);

    try std.testing.expect(std.mem.indexOf(u8, rendered, "CONFIG_A=y") != null);
    try std.testing.expect(std.mem.indexOf(u8, rendered, "# CONFIG_B is not set") != null);
    try std.testing.expect(std.mem.indexOf(u8, rendered, "CONFIG_C=\"hello\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, rendered, "CONFIG_D=42") != null);
    try std.testing.expect(std.mem.indexOf(u8, rendered, "CONFIG_E=0x8000") != null);
}

test "render rejects conflicting values on same key" {
    const docs = [_]ModuleDoc{
        .{
            .name = "core",
            .entries = &.{Entry.flag("CONFIG_DUP", true)},
        },
        .{
            .name = "freertos",
            .entries = &.{Entry.flag("CONFIG_DUP", false)},
        },
    };

    try std.testing.expectError(
        error.ConfigKeyConflict,
        render(std.testing.allocator, &docs),
    );
}

test "render deduplicates repeated same key and value" {
    const docs = [_]ModuleDoc{
        .{
            .name = "core",
            .entries = &.{Entry.flag("CONFIG_SAME", true)},
        },
        .{
            .name = "alias",
            .entries = &.{Entry.flag("CONFIG_SAME", true)},
        },
    };

    const rendered = try render(std.testing.allocator, &docs);
    defer std.testing.allocator.free(rendered);

    try std.testing.expectEqual(@as(usize, 1), std.mem.count(u8, rendered, "CONFIG_SAME=y"));
}
